# Generated by Django 4.1.5 on 2023-04-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('dascrition', models.TextField()),
                ('category', models.CharField(choices=[('TO', 'Top'), ('SK', 'Skirt'), ('PA', 'Pants'), ('SH', 'Shorts')], max_length=2)),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
